device: /dev/ttyACM0
frame_id: gps
uart1:
  baudrate: 115200
config_on_startup: false
rate: 1 # in Hz
nav_rate: 1 # [# of measurement cycles], recommended 1 Hz, may
tmode3: 0
gnss:
  glonass: true # Supported by C94-M8P
  beidou: true # Supported by C94-M8P
  galileo: true
  qzss: false # Supported by C94-M8P

publish:
  all: true
  # rxm:
  #   raw: true
  # nav:
  #   status: true
  #   pvt: true
  #   posecef: false
  #   hpposllh: true
